---

- name: load variables
  include_vars:
    file: "{{ map }}.yml"
    name: "{{ map }}"
  loop:
    - default
    - osfamilymap
    - distributionmap
    - fingerprintmap
  loop_control:
    loop_var: map

- name: compute configuration
  set_fact:
    pacman: "{{ default.pacman | combine(
      osfamilymap[ansible_os_family].pacman is defined | ternary(osfamilymap[ansible_os_family].pacman, {}),
      distributionmap[ansible_distribution].pacman is defined | ternary(distributionmap[ansible_distribution].pacman, {}),
      pacman | default({}),
      recursive=True
      ) }}"
