---

pacman:
  package: pacman
  config_file: /etc/pacman.conf
  config:
    options:
      UseSyslog: False
      Color: False
      NoProgresssBar: False
      CheckSpace: True
      VerbosePkgLists: False
      ILoveCandy: False
