---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: archlinux-${TOX_ENVNAME}
    image: docker.io/archlinux:latest
    dockerfile: Dockerfile.j2
  - name: manjaro-${TOX_ENVNAME}
    image: docker.io/manjarolinux/base:latest
    dockerfile: Dockerfile.j2
provisioner:
  name: ansible
verifier:
  name: ansible
