---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: Archlinux
    image: docker.io/archlinux:latest
    dockerfile: Dockerfile.j2
    pre_build_image: true
  - name: Manjaro
    image: docker.io/manjarolinux/base:latest
    dockerfile: Dockerfile.j2
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
