---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Archlinux
    image: archlinux:latest
    dockerfile: Dockerfile.j2
  - name: Manjaro
    image: manjarolinux/base:latest
    dockerfile: Dockerfile.j2
provisioner:
  name: ansible
verifier:
  name: ansible
