---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Archlinux
    image: archlinux:latest
    pre_build_image: true
  - name: Manjaro
    image: manjarolinux/base:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
